
  List<String> barriosMontevideo = [
  'Aires Puros',
  'Atahualpa',
  'Bañados de Carrasco',
  'Barrio Sur',
  'Bella Italia',
  'Bella Vista',
  'Buceo',
  'Capurro',
  'Carrasco',
  'Carrasco Norte',
  'Centro',
  'Cerro Norte',
  'Ciudad Vieja',
  'Cordón',
  'Flor de Maroñas',
  'Ituzaingó',
  'Jacinto Vera',
  'Jardines del Hipódromo',
  'La Blanqueada',
  'La Comercial',
  'La Teja',
  'La Unión',
  'Las Acacias',
  'Lezica',
  'Malvín',
  'Malvín Norte',
  'Manga',
  'Maroñas',
  'Mercado Modelo',
  'Palermo',
  'Parque Batlle',
  'Parque Rodó',
  'Paso de las Duranas',
  'Peñarol',
  'Pérez Castellano',
  'Piedras Blancas',
  'Playa Hermosa',
  'Pocitos',
  'Prado',
  'Prado - Nueva Savona',
  'Punta Carretas',
  'Punta Gorda',
  'Punta Rieles',
  'Reducto',
  'Sayago',
  'Tres Cruces',
  'Unión',
  'Villa Biarritz',
  'Villa Colón',
  'Villa del Cerro',
  'Villa Dolores',
  'Villa Don Bosco',
  'Villa Española',
  'Villa Ferrando',
  'Villa García',
  'Villa Hortensia',
  'Villa Muñoz',
  'Villa Serrana',
  'Yaguaron',
];